# user  nobody;
worker_processes 8;
worker_rlimit_nofile 100000;

pid logs/nginx.pid;

events {
    worker_connections 10240;
}

http {
    include mime.types;
    default_type application/octet-stream;
    #access_log  logs/access.log  main;

    sendfile on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout 65;

    #gzip  on;

    server {
        listen 80;
        # Redirect port 80 to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 8443 ssl;
        server_name ;  # Fill in domain

        ssl_certificate ;  # Certificate path
        ssl_certificate_key ;  # Private key path

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            add_header Access-Control-Allow-Origin *;
            add_header Content-Type text/plain;
            return 200 "hello world";
        }
    }

}

stream {
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    log_format proxy '$proxy_protocol_addr $geoip_country_code $remote_addr [$time_local] '
    '$protocol $status $bytes_sent $bytes_received '
    '$session_time "$upstream_addr" "$ssl_preread_server_name" '
    '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';

    access_log /usr/logs/access.log proxy;

    map_hash_bucket_size 64;

    map $ssl_preread_server_name $backend_pool {
        www.notion.so server_notion;
        s3.us-west-2.amazonaws.com server_s3;
        msgstore.www.notion.so server_msg;
        notion.so server_n;
        exp.notion.so server_exp;
        api.pgncs.notion.so server_api;
    }

    upstream server_msg {
        server msgstore.www.notion.so:443 ;
    }

    upstream server_n {
        server notion.so:443;
    }

    upstream server_notion {
        server www.notion.so:443;
    }

    upstream server_s3 {
        server s3.us-west-2.amazonaws.com:443;
    }

    upstream server_api {
        server api.pgncs.notion.so:443;
    }

    upstream server_exp {
        server exp.notion.so:443;
    }

    # Rate limiting
    map $ssl_preread_server_name $upspeed {
        www.notion.so 1536k;
        s3.us-west-2.amazonaws.com 1024k;
        msgstore.www.notion.so 256k;
        notion.so 256k;
        api.pgncs.notion.so 256k;
        exp.notion.so 256k;

    }

    map $ssl_preread_server_name $downspeed {
        www.notion.so 1536k;
        s3.us-west-2.amazonaws.com 512k;
        msgstore.www.notion.so 256k;
        notion.so 256k;
        api.pgncs.notion.so 256k;
        exp.notion.so 256k;
    }

    server {
        listen 443;
        ssl_preread on;
        proxy_pass $backend_pool;
        proxy_connect_timeout 15s;
        proxy_timeout 60s;
        proxy_next_upstream_timeout 15s;
        proxy_download_rate $downspeed;
        proxy_upload_rate $upspeed;
        # Block connections outside mainland China
        include geocn.conf;
    }
}
